# Taguchi Loss Function Analysis

Process behavior charts answer *"Is this process stable?"*  The Taguchi Loss Function (Bishop Chapter 15) answers a different question: *"Where is the variation coming from, and how much does each source contribute to expected loss?"*

It decomposes the expected squared loss into **5 components**:

| Component | Label | What It Measures |
|-----------|-------|-----------------|
| **Centering** | MEAN | Loss from process mean being off-target |
| **Unexplained** | UNEXPLAINED | Within-cell variation (noise floor) |
| **PDC** | PDC | Variation due to Process Design Conditions (factor levels) |
| **Time** | PT | Variation due to Production Time (temporal drift) |
| **Interaction** | PDCxPT INT | Variation from PDC-by-time interaction (inconsistent factor effects over time) |

The Pareto ranking tells the analyst which source of variation to attack first for the greatest reduction in loss.

## What You'll Learn

1. Assess loss function decomposition with `study.loss_function(target=)`
2. Read and interpret the 5-component Pareto breakdown
3. Visualize unstructured (5-bar) and structured (7-bar) Pareto charts
4. Access PDC decomposition by individual factor
5. Verify the decomposition identity (5 components = total)
6. Understand when the loss function is unavailable

---

## Setup

We use Bishop's PBTESTDATABASE_T100 — a 4000-row validation dataset with 4 factor levels x 2 factor levels x 100 time periods, and response columns designed to exercise each Design State (DS).

In [1]:
from processbehavior import ProcessBehavior

# Load the PBTESTDATABASE_T100
pb = ProcessBehavior.read_csv('../../validation/PBTESTDATABASE_T100.csv')

print(f"Dataset: {pb.data.shape[0]} rows x {pb.data.shape[1]} columns")
print(f"Columns: {pb.data.columns.tolist()}")

Dataset: 4000 rows x 11 columns
Columns: ['PRODUCTION TIME', 'FACTOR 1', 'FACTOR 2', 'FACTOR 1xFACTOR 2', 'PM SDS 1', 'PM SDS 2', 'PM SDS 3', 'PM SDS 4', 'PM SDS 5', 'PM SDS 6', 'PM INERT']


/var/folders/cp/dvnklhkn2dd12f_pgg5mhydw0000gp/T/ipykernel_38949/3003584475.py:4: ProcessBehaviorWarning: Found 11655 garbage/NA values across 5 column(s):
  • PM SDS 2: 3200 values
  • PM SDS 3: 958 values
  • PM SDS 4: 2134 values
  • PM SDS 5: 3359 values
  • PM SDS 6: 2004 values

These values were converted to NA and will be excluded from analysis.
  pb = ProcessBehavior.read_csv('../../validation/PBTESTDATABASE_T100.csv')


In [2]:
# Formulate a DS 1 study (full replication — has VAS residuals)
study = pb.formulate(
    response='PM SDS 1',
    factors=['FACTOR 1', 'FACTOR 2'],
    time='PRODUCTION TIME',
    precision=3
)

print(study)

Study(response='PM SDS 1', factors=[FACTOR 1, FACTOR 2], time='PRODUCTION TIME', ads=1)
  Valid: Histogram, Xbar, S, X, mR | Recommended: Xbar
  Residuals: R1, R2, R3, R4, R5, R6
  → study.execute() or study.support for details


---

## Basic Loss Assessment

Call `study.loss_function(target=)` to decompose expected loss relative to a target value. The target of 237 reproduces Tom's reference output:

In [3]:
result = study.loss_function(target=237.0)
result

LossResult:
  Target=237.0, Ybar=237.817, N=4000
  K=8 PDC levels, T=100 periods, SDS=1

  Expected Loss (EL) = 3.856

  Loss Decomposition:
         PDCxPT INT: 44.511%
        UNEXPLAINED: 20.869%
               MEAN: 17.304%
                PDC: 14.559%
                 PT: 2.757%

  PDC Decomposition:
           FACTOR 1: 9.183%
           FACTOR 2: 3.818%
            PDF INT: 1.559%

### Reading the Output

The Pareto ranking tells you where to focus improvement efforts:

- **PDCxPT INT** (largest) — factor effects are inconsistent over time. This is the dominant source of loss — the interaction between process design conditions and production time.
- **UNEXPLAINED** — within-cell noise floor. This is the irreducible variation given the current measurement and process design.
- **MEAN** — the process mean is off-target. Adjusting the process center toward T=237 would reduce this component.
- **PDC** — variation due to factor levels. Some factor combinations produce systematically different results.
- **PT** (smallest) — temporal drift is minimal. The process mean is relatively stable over time.

In [4]:
# Verify against Tom's VAS run of 3 October 2026 (PM SDS 1, T=237)
print("Loss Decomposition (Tom's reference):")
print(f"  PDCxPT INT:   {result.pct_interaction:.1f}%  (expected: 44.5%)")
print(f"  UNEXPLAINED:  {result.pct_unexplained:.1f}%  (expected: 20.9%)")
print(f"  MEAN:         {result.pct_centering:.1f}%  (expected: 17.3%)")
print(f"  PDC:          {result.pct_pdc:.1f}%  (expected: 14.6%)")
print(f"  PT:           {result.pct_time:.1f}%  (expected: 2.8%)")

Loss Decomposition (Tom's reference):
  PDCxPT INT:   44.5%  (expected: 44.5%)
  UNEXPLAINED:  20.9%  (expected: 20.9%)
  MEAN:         17.3%  (expected: 17.3%)
  PDC:          14.6%  (expected: 14.6%)
  PT:           2.8%  (expected: 2.8%)


---

## Visualizing: Unstructured Pareto

`result.plot()` produces a horizontal bar chart of the 5 components in Pareto order (Fig 15-4). The largest contributor to loss appears at the top:

In [5]:
result.plot().show()

---

## Visualizing: Structured Pareto

`result.plot(structured=True)` expands the PDC bar into its per-factor components (Fig 15-5). Instead of one "PDC" bar, you see:

- **F1**, **F2** — main effect loss for each factor
- **PDF INT** — the factor interaction loss (PDC minus individual factor contributions)

This gives the analyst a more actionable view: which specific factor is contributing most to PDC loss?

In [6]:
result.plot(structured=True).show()

### Interpreting the Pareto

Read the Pareto top-down. The largest percentage is the biggest lever for improvement:

1. **PDCxPT INT (44.5%)** — the factor-by-time interaction dominates. Factor effects are not consistent over time. This is an assignable cause that warrants investigation.
2. **UNEXPLAINED (20.9%)** — the noise floor. Reducing this requires fundamentally changing the measurement or process.
3. **MEAN (17.3%)** — re-centering the process on the target would eliminate this component entirely.
4. **F1 (9.2%)** — FACTOR 1 main effect contributes more than FACTOR 2.
5. **F2 (3.8%)** — FACTOR 2 contributes less individually.
6. **PT (2.8%)** — temporal drift is small.
7. **PDF INT (1.6%)** — the interaction between the two factors is small.

---

## PDC Decomposition

When there are multiple factors, PDC decomposes into per-factor main effect losses plus a factor interaction term. Access these via `result.pdc_by_factor` and `result.pdc_factor_interaction`:

In [7]:
# Per-factor PDC breakdown
print("PDC by factor:")
for factor, loss_val in result.pdc_by_factor.items():
    pct = loss_val / result.total * 100
    print(f"  {factor}: {pct:.1f}%")

pdc_int_pct = result.pdc_factor_interaction / result.total * 100
print(f"  PDF INT: {pdc_int_pct:.1f}%")

# Verify identity: F1 + F2 + PDF INT = PDC
pdc_sum = sum(result.pdc_by_factor.values()) + result.pdc_factor_interaction
print(f"\nF1 + F2 + PDF INT = {pdc_sum:.6f}")
print(f"PDC               = {result.pdc:.6f}")
print(f"Match: {abs(pdc_sum - result.pdc) < 1e-10}")

PDC by factor:
  FACTOR 1: 9.2%
  FACTOR 2: 3.8%
  PDF INT: 1.6%

F1 + F2 + PDF INT = 0.561437
PDC               = 0.561437
Match: True


---

## Default Target

When no target is specified, the loss function defaults to the grand mean. This sets the centering component to zero — useful when you want to focus purely on variance decomposition:

In [8]:
result_default = study.loss_function()

print(f"Target: {result_default.target:.3f} (grand mean)")
print(f"Target is default: {result_default.target_is_default}")
print(f"Centering: {result_default.pct_centering:.1f}%")
print()
print("Without centering loss, the remaining 4 components")
print("share 100% of the total:")
print(f"  UNEXPLAINED:  {result_default.pct_unexplained:.1f}%")
print(f"  PDC:          {result_default.pct_pdc:.1f}%")
print(f"  PT:           {result_default.pct_time:.1f}%")
print(f"  PDCxPT INT:   {result_default.pct_interaction:.1f}%")

Target: 237.817 (grand mean)
Target is default: True
Centering: 0.0%

Without centering loss, the remaining 4 components
share 100% of the total:
  UNEXPLAINED:  25.2%
  PDC:          17.6%
  PT:           3.3%
  PDCxPT INT:   53.8%


---

## Decomposition Identity

The 5 components always sum exactly to the total expected loss. This is an algebraic identity, not an approximation:

In [9]:
# 5 components sum to total
component_sum = (
    result.centering + result.unexplained + result.pdc +
    result.time + result.interaction
)

print(f"Centering:    {result.centering:.6f}")
print(f"Unexplained:  {result.unexplained:.6f}")
print(f"PDC:          {result.pdc:.6f}")
print(f"Time:         {result.time:.6f}")
print(f"Interaction:  {result.interaction:.6f}")
print(f"{'─' * 30}")
print(f"Sum:          {component_sum:.6f}")
print(f"Total:        {result.total:.6f}")
print(f"Match: {abs(component_sum - result.total) < 1e-10}")
print()
print(f"Percentages sum: {result.pct_centering + result.pct_unexplained + result.pct_pdc + result.pct_time + result.pct_interaction:.1f}%")

Centering:    0.667270
Unexplained:  0.804736
PDC:          0.561437
Time:         0.106317
Interaction:  1.716448
──────────────────────────────
Sum:          3.856207
Total:        3.856207
Match: True

Percentages sum: 100.0%


---

## The `as_dict()` Method

For programmatic use or export, `as_dict()` returns a rounded dictionary. You can override the rounding precision:

In [10]:
result.as_dict(round_to=4)

{'target': 237.0,
 'target_is_default': False,
 'y_bar': 237.8169,
 'n': 4000,
 'K': 8,
 'T_periods': 100,
 'sds': 1,
 'centering': 0.6673,
 'unexplained': 0.8047,
 'pdc': 0.5614,
 'time': 0.1063,
 'interaction': 1.7164,
 'total': 3.8562,
 'pct_centering': 17.3038,
 'pct_unexplained': 20.8686,
 'pct_pdc': 14.5593,
 'pct_time': 2.757,
 'pct_interaction': 44.5113,
 'pdc_by_factor': {'FACTOR 1': 0.3541, 'FACTOR 2': 0.1472},
 'pdc_factor_interaction': 0.0601}

---

## DS 2: ADS 2/3 Unexplained and Interaction

DS 2 has singleton cells, so there is no within-cell spread to average. The unexplained component is the sample variance of R2 (10-1 manual Eq 15-17), and the interaction is what the other four components leave of the total loss $(\bar{Y}_{..} - T)^2 + S^2$, set to 0 if negative (Eqs 15-18 to 15-20). With one observation per subgroup, interaction and noise cannot be separated cell by cell, so the interaction is backed out of the total rather than estimated directly:

In [11]:
# DS 2 — one observation per cell
study_sds2 = pb.formulate(
    response='PM SDS 2',
    factors=['FACTOR 1', 'FACTOR 2'],
    time='PRODUCTION TIME',
    precision=3
)

result_sds2 = study_sds2.loss_function(target=237.0)
print(f"DS: {result_sds2.sds}")
print(f"N={result_sds2.n}, K={result_sds2.K}, T={result_sds2.T_periods}")
print()
result_sds2

DS: 2
N=800, K=8, T=100



LossResult:
  Target=237.0, Ybar=237.782, N=800
  K=8 PDC levels, T=100 periods, SDS=2

  Expected Loss (EL) = 2.909

  Loss Decomposition:
        UNEXPLAINED: 30.045%
         PDCxPT INT: 25.608%
               MEAN: 21.039%
                PDC: 20.369%
                 PT: 2.939%

  PDC Decomposition:
           FACTOR 1: 13.66%
           FACTOR 2: 5.459%
            PDF INT: 1.25%

---

## Single Factor

With only one factor, there is no factor interaction. `pdc_factor_interaction` is zero, and the structured plot shows the single factor bar instead of PDC:

In [12]:
# Single factor — no factor interaction
study_1f = pb.formulate(
    response='PM SDS 1',
    factors=['FACTOR 1'],
    time='PRODUCTION TIME',
    precision=3
)

result_1f = study_1f.loss_function(target=237.0)
print(f"PDC by factor: {result_1f.pdc_by_factor}")
print(f"Factor interaction: {result_1f.pdc_factor_interaction}")
print()
result_1f

PDC by factor: {'FACTOR 1': 0.3541064951990689}
Factor interaction: 0.0



LossResult:
  Target=237.0, Ybar=237.817, N=4000
  K=4 PDC levels, T=100 periods, SDS=1

  Expected Loss (EL) = 3.94

  Loss Decomposition:
        UNEXPLAINED: 62.028%
               MEAN: 16.937%
         PDCxPT INT: 9.347%
                PDC: 8.988%
                 PT: 2.699%

---

## When Loss Function Is Unavailable

The loss function requires VAS residuals — which means the study must have both **factors** and **time**. Without time, VAS residuals are not computed, and `loss_function()` raises a `ValidationError`:

In [13]:
# Without time — no VAS residuals
study_no_time = pb.formulate(
    response='PM SDS 1',
    factors=['FACTOR 1', 'FACTOR 2'],
)

try:
    study_no_time.loss_function(target=237.0)
except Exception as e:
    print(f"{type(e).__name__}: {e}")

ValidationError: Loss function analysis requires VAS residuals (factors + time design). Current design (SDS 1) does not have VAS residuals.


---

## The Equations

For reference, here are the Bishop Chapter 15 equations implemented by `loss_function()`:

**Expected Loss Decomposition** (Eq. 15-13):

$$EL = (\bar{Y}_{..} - T)^2 + \hat{\sigma}^2_w + \frac{1}{K}\sum_k \rho_k^2 + \frac{1}{T}\sum_t \tau_t^2 + \frac{1}{KT}\sum_{k,t} (\rho\tau)_{kt}^2$$

Where the 5 terms are:

| Term | Component | Equation |
|------|-----------|----------|
| $(\bar{Y}_{..} - T)^2$ | Centering | Squared distance from grand mean to target |
| $\hat{\sigma}^2_w$ | Unexplained | Noise variance (Eq. 15-16 / 15-17) |
| $\frac{1}{K}\sum_k \rho_k^2$ | PDC | Mean squared PDC effect (Eq. 15-22) |
| $\frac{1}{T}\sum_t \tau_t^2$ | Time | Mean squared time effect |
| $\frac{1}{KT}\sum_{k,t} (\rho\tau)_{kt}^2$ | Interaction | Mean squared PDC x time interaction (DS 1/4); remainder (DS 2/3/5/6) |

Equation numbers are those of Bishop's VAS manual dated 10-1-2026.

**Replicated cells** (ADS 1, Eq. 15-16) — the average cell variance:

$$\hat{\sigma}^2_w = \frac{1}{KT}\sum_{k,t} S_{kt}^2$$

**Singleton cells** (ADS 2/3) — the variance of R2 (Eq. 15-17), and the interaction as the remainder of the total loss (Eqs. 15-18 to 15-20), floored at 0:

$$\hat{\sigma}^2_w = S_{R2}^2 \qquad EL_{PDC\times PT} = \max\left(S^2 - \frac{1}{K}\sum_k \rho_k^2 - \frac{1}{T}\sum_t \tau_t^2 - S_{R2}^2,\ 0\right)$$

where $S^2$ is the sample variance of all observations.

**Effects**:

$$\rho_k = \bar{Y}_{k.} - \bar{Y}_{..} \qquad \tau_t = \bar{Y}_{.t} - \bar{Y}_{..} \qquad (\rho\tau)_{kt} = \bar{Y}_{kt} - \bar{Y}_{k.} - \bar{Y}_{.t} + \bar{Y}_{..}$$

---

## Summary

| Concept | Key Point |
|---------|----------|
| `study.loss_function(target=)` | Decompose expected loss — no re-formulation needed |
| 5 components | Centering, Unexplained, PDC, Time, Interaction |
| Pareto ranking | Largest % = biggest improvement lever |
| `result.plot()` | Unstructured Pareto (5 bars) |
| `result.plot(structured=True)` | Structured Pareto — PDC split into per-factor bars |
| `pdc_by_factor` | Per-factor main effect losses (multi-factor) |
| Default target | Target = grand mean, centering = 0 |
| Identity | 5 components sum exactly to total |
| DS 2/3 | Unexplained is the variance of R2; interaction is the remainder of the total loss |
| Requires | Factors + time (VAS residuals) |

## Next Steps

- [Process Capability](process-capability.ipynb) — assess capability against specification limits
- [DS Validation](sds-validation.ipynb) — see how DS affects available analyses
- [Complete DS 1 Analysis](sds1-complete-analysis.ipynb) — full deep dive with VAS residuals